# Generated by Django 4.1.7 on 2023-03-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('specialtiy', models.CharField(max_length=200)),
                ('rating', models.IntegerField(max_length=10)),
            ],
        ),
    ]
