# Generated by Django 4.1.7 on 2023-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalinfo', '0003_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=200)),
                ('dosage_form', models.CharField(max_length=200)),
                ('dosageStrength', models.FloatField()),
                ('indications', models.CharField(max_length=200)),
                ('contradictions', models.CharField(max_length=200)),
                ('side_effect', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
