# Generated by Django 4.1.7 on 2023-03-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalinfo', '0004_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='contradictions',
            field=models.CharField(max_length=1200),
        ),
    ]
